model_type : yolov5
backbone : large_p6
img_size : [1024,896]
pretrained : null
#img_size : 960

model:
  _target_ : mt.modules.yolov5.YoloV5Module
  model :
    _target_ : mt.models.yolov5.model
    device:
      _target_ : torch.device
      device : 'cuda'
    backbone :
      _target_ : mt.models.yolov5.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
#    img_size : ${module.img_size}
    img_size :  1024
  learning_rate : 1e-4
  weight_decay : 1e-6
