rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/map_50"
  mode: "max" # "max" means higher metric value is better, can be also "min"
  save_top_k: 1
  save_last: True
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}_{val/map_50:.3f}"
  auto_insert_metric_name: False
  save_weights_only : True

stochastic_weight_averaging:
  _target_: pytorch_lightning.callbacks.StochasticWeightAveraging
  swa_epoch_start : 10
  swa_lrs : 1e-5

