model_type : mmdet.detr
backbone : r50_8x2_150e_coco
img_size : [1024,896]

model:
  _target_ : mt.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : mt.models.mmdet.detr.model
    backbone :
      _target_ : mt.models.mmdet.detr.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
  learning_rate : 1e-4
