model_type : efficientdet
backbone : tf_d4
img_size : [1024,896]

model :
  _target_ : src.modules.efficientdet.EfficientDetModule
  model :
    _target_ : src.models.efficientdet.model
    backbone :
      _target_ : src.models.efficientdet.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
    img_size : ${module.img_size}
  learning_rate : 1e-4
  optimizer : "adam"
  weight_decay : 1e-6
