model_type : efficientdet
backbone : tf_d4
img_size : 1024

model :
  _target_ : src.lightning_modules.efficientdet.EfficientDetModule
  model :
    _target_ : src.lightning_modules.models.efficientdet.model
    backbone :
      _target_ : src.lightning_modules.models.efficientdet.backbones.${backbone}
      pretrained : 0
    num_classes : 2
    img_size : ${module.img_size}
  learning_rate : 1e-4
  optimizer : "adam"
  weight_decay : 1e-6
