model_type : mmdet.faster_rcnn
backbone : resnet50_fpn_1x
img_size : [1024,896]

model:
  _target_ : mt.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : mt.models.mmdet.faster_rcnn.model
    backbone :
      _target_ : mt.models.mmdet.faster_rcnn.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
  learning_rate : 1e-4
  weight_decay : 1e-6
  optimizer : 'adamW'
#    img_size : ${module.img_size}
