model_type : mmdet.faster_
backbone : resnet50_fpn_1x
img_size : [1024, 768]

model:
  _target_ : src.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : src.models.mmdet.faster_rcnn.model
    backbone :
      _target_ : src.models.mmdet.faster_rcnn.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
#    img_size : ${module.img_size}
