model_type : mmdet.retinanet
backbone : resnet50_fpn_1x
img_size : [1024,896]

model:
  _target_ : mt.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : mt.models.mmdet.retinanet.model
    backbone :
      _target_ : mt.models.mmdet.retinanet.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
  optimizer : adamW
  learning_rate : 1e-4
#    img_size : ${module.img_size}
