model_type : mmdet.yolox
backbone : yolox_tiny_8x8
img_size : [1024,896]

model:
  _target_ : mt.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : mt.models.mmdet.yolox.model
    backbone :
      _target_ : mt.models.mmdet.yolox.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
  learning_rate : 1e-4
