model_type : yolov5
backbone : large_p6
img_size : 896

model:
  _target_ : src.modules.yolov5.YoloV5Module
  model :
    _target_ : src.models.yolov5.model
    backbone :
      _target_ : src.models.yolov5.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
    img_size : ${module.img_size}
  learning_rate : 1e-4
  weight_decay : 1e-6
