model_type : mmdet.yolo3
backbone : darknet53s
img_size : [1024,896]

model:
  _target_ : mt.modules.mmdet_adapter.MMDetModelAdapter
  model :
    _target_ : mt.models.mmdet.yolo3.model
    backbone :
      _target_ : mt.models.mmdet.yolo3.backbones.${module.backbone}
      pretrained : 1
    num_classes : 2
  learning_rate : 1e-4
