_target_ : src.transforms.transforms_composer.TransformsComposer
cfg :
  image_size : 1024
  HorizontalFlip:
    apply : True
    transform :
      _target_ : albumentations.HorizontalFlip
      p : 0.5