_target_ : src.datamodules.dental_caries.DentalCaries
data_root : /datagrid/personal/kuntluka/dental_merged
model_type : ${module.model_type}
ann_file : 'annotations2.json'
batch_size : 1
num_workers : 8
limit_train_samples : null
train_val_test_split: [0.7, 0.15, 0.15]
seed : ${seed}
