_target_ : src.datamodules.dental_caries.DentalCaries
data_root : /datagrid/personal/kuntluka/dental_merged
image_size : ${module.img_size}
model_type : ${module.model_type}
ann_file : 'annotations2.json'
batch_size : 1
num_workers : 8
limit_train_samples : null
train_val_test_split: [0.8, 0.1, 0.1]
seed : ${seed}
