_target_ : mt.datamodules.dental.DentalCaries
data_root : /datagrid/personal/kuntluka/dental_rtg
model_type : ${module.model_type}
ann_file : 'caries6.json'
batch_size : 1
num_workers : 8
limit_train_samples : null
train_val_test_split: [0.7, 0.15, 0.15]
seed : ${seed}
